services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "5203:5203"
    depends_on:
      - sqlserver
      - mssqltools
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - DOTNET_WATCH_RESTART_ON_RUDE_EDIT=1
    container_name: quave_backend
    volumes_from:
      - dockersock

  dockersock:
    image: alpine:latest
    container_name: dockersock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: /bin/sh -c "sleep infinity"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WDS_SOCKET_PORT=0
      - VITE_APP_HOST=0.0.0.0
    command: npm start
    ports:
      - "3000:3000"

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=QuaveRoot123!
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql

  mssqltools:
    image: mcr.microsoft.com/mssql-tools
    container_name: mssqltools
    depends_on:
      - sqlserver
    volumes:
      - ./db/init-db.sh:/tmp/init-db.sh
    command: /bin/bash ./tmp/init-db.sh

volumes:
  sqlserver_data: