services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - sqlserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    working_dir: /app/frontend
    volumes:
      - ./frontend:/app/frontend
    command: npm start
    ports:
      - "3000:3000"

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=QuaveRoot123!
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql

  mssqltools:
    image: mcr.microsoft.com/mssql-tools
    depends_on:
      - sqlserver
    volumes:
      - ./db/init-db.sh:/tmp/init-db.sh
    command: /bin/bash ./tmp/init-db.sh

volumes:
  sqlserver_data: