FROM mcr.microsoft.com/dotnet/sdk:8.0

WORKDIR /app/backend

RUN apt-get update && apt-get install -y dos2unix

COPY . .

RUN dotnet tool install --global dotnet-ef

ENV PATH="${PATH}:/root/.dotnet/tools"

RUN dos2unix entrypoint.sh && chmod +x entrypoint.sh

EXPOSE 5000

ENTRYPOINT ["./entrypoint.sh"] 